---
- name: Remove webserver
  hosts: all
  become: true
  tasks:
    - name: httpd service stop
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: stopped
    - name: Change default gateway
      shell: "ip route add default via 192.168.64.1 dev enp0s1"
    - name: httpd uninstalled
      ansible.builtin.yum:
        name: httpd
        state: absent
