#PHP Settings
php_modules: [ 'php', 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'xmlrpc-c', 'php-soap', 'php-intl', 'php-zip' ]
 
#MySQL Settings
mysql_root_password: "P@ssw0rd"
mysql_db: "wpdb"
mysql_user: "wpuser"
mysql_password: "password"
 
#HTTP Settings
http_host: "wptest"
http_conf: "wptest.conf"
http_port: "80"
